
services:

  # Link Reduction - Основное приложение
  app:
    container_name: link-reduction-app
    build:
      context: .                        # Контекст сборки — корень проекта
      dockerfile: Dockerfile            # Путь к Dockerfile основного приложения
    ports:
      - "8080:8080"                     # Пробрасываем порт: хост:контейнер

    restart: always                     # Перезапуск при сбое
    env_file:
      - .env                            # Загружаем переменные окружения из .env файла
    depends_on:
      - db                              # Ожидаем готовности БД
      - redis                           # Ожидаем готовности Redis (если используется кэш)
    networks:
      - lr-network                     # Общая сеть для связи с другими сервисами

  # 🐘 PostgreSQL — основная реляционная база данных
  db:
    restart: always
    image: postgres:15
    environment:
      POSTGRES_USER: user             # Имя пользователя для подключения к БД
      POSTGRES_PASSWORD: password     # Пароль пользователя
      POSTGRES_DB: postgres           # Имя создаваемой базы данных
    volumes:
      - db-data:/var/lib/postgresql/data  # Хранилище данных базы (сохраняется при перезапуске)
    ports:
      - "5432:5432"                   # Проброс порта PostgreSQL наружу
    networks:
      - lr-network                   # Общая сеть между контейнерами

  # 🧠 Redis — in-memory key-value хранилище + возможный gRPC-контейнер
  redis:
    image: redis:7-alpine          # Используем официальный облегчённый образ Redis
    ports:
      - "6379:6379"               # Открываем стандартный порт Redis
    restart: always               # Автоматический рестарт контейнера
    volumes:
      - redis_data:/data          # Храним данные Redis на volume
    networks:
      - lr-network               # Подключаем к нужной сети

  # 📈 Prometheus — система сбора и мониторинга метрик
  prometheus:
      image: prom/prometheus:latest
      ports:
        - "9090:9090"
      volumes:
        - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      networks:
        - lr-network

  # 🟡 Kafka (режим KRaft, без Zookeeper) — брокер сообщений
  kafka:
    image: bitnami/kafka:3.6.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ENABLE_KRAFT: "yes"
      KAFKA_CFG_PROCESS_ROLES: "broker,controller"
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_LISTENERS: "PLAINTEXT://:9092,CONTROLLER://:9093"
      KAFKA_CFG_ADVERTISED_LISTENERS: "PLAINTEXT://kafka:9092"
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_KRAFT_CLUSTER_ID: "abcdefghijklmnopqrstuv"
      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - lr-network

  # 📊 Grafana — визуализация метрик из Prometheus и других источников
  grafana:
    image: grafana/grafana:10.2.2
    ports:
      - "3000:3000"                        # Веб-интерфейс Grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin      # Логин администратора
      - GF_SECURITY_ADMIN_PASSWORD=admin  # Пароль администратора
    restart: always
    depends_on:
      - prometheus                              # Ожидаем запуска prometheus (контейнера пока нет в списке)
    networks:
      - lr-network

volumes:
  db-data:        # Volume для хранения данных PostgreSQL
  redis_data:     # Volume для хранения данных Redis

networks:
  lr-network:    # Общая bridge-сеть, чтобы контейнеры "видели" друг друга по имени
    driver: bridge
